version: '3'
services:
  registry:
    image: redis:alpine
    ports:
      - 6379:6379
  main:
    build:
      context: .
      dockerfile: Dockerfile_service_registry
      args:
        - FILENAME=main.py
        - HOST=0.0.0.0
        - PORT=8000
        - SERVICE_REGISTRY_HOST=registry
        - SERVICE_REGISTRY_PORT=6379
    ports:
      - 8000:8000
    depends_on:
      - registry
  service_discovery:
    build:
      context: .
      dockerfile: Dockerfile_service_registry
      args:
        - FILENAME=service_discovery.py
        - HOST=0.0.0.0
        - PORT=8001
        - SERVICE_REGISTRY_HOST=registry
        - SERVICE_REGISTRY_PORT=6379
    ports:
      - 8001:8001
    depends_on:
      - registry
  entity_recognition:
    build:
      context: .
      dockerfile: Dockerfile_api
      args:
        - FILENAME=entity_recognition.py
        - HOST=0.0.0.0
        - PORT=8002
    ports:
      - 8002:8002
  sentiment_analysis:
    build:
      context: .
      dockerfile: Dockerfile_api
      args:
        - FILENAME=sentiment_analysis.py
        - HOST=0.0.0.0
        - PORT=8003
    ports:
      - 8003:8003
  word_count:
    build:
      context: .
      dockerfile: Dockerfile_api
      args:
        - FILENAME=word_count.py
        - HOST=0.0.0.0
        - PORT=8004
    ports:
      - 8004:8004
  test:
    build:
      context: .
      dockerfile: Dockerfile_test
    env_file:
      - test/.env